"""modified remunerations table

Revision ID: 6a1fc749acbd
Revises: 6abc97b1d922
Create Date: 2024-02-18 14:32:41.628720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1fc749acbd'
down_revision = '6abc97b1d922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remunerations', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remunerations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
