"""altered training table

Revision ID: 740f71aa737c
Revises: 6a1fc749acbd
Create Date: 2024-02-19 10:53:25.892022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740f71aa737c'
down_revision = '6a1fc749acbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
