"""upgrade tables

Revision ID: 9f7de3d671ca
Revises: 6abc97b1d922
Create Date: 2024-02-18 13:01:36.817920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7de3d671ca'
down_revision = '6abc97b1d922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_leave_approvals_leave_id_leaves'), 'leaves', ['leave_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leave_approvals_leave_id_leaves'), type_='foreignkey')
        batch_op.drop_column('leave_id')

    # ### end Alembic commands ###
