"""altered leave tables

Revision ID: cfd489c9873a
Revises: 740f71aa737c
Create Date: 2024-02-19 11:19:49.812785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd489c9873a'
down_revision = '740f71aa737c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_manager', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_hr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_approvals', schema=None) as batch_op:
        batch_op.drop_column('approved_by_hr')
        batch_op.drop_column('approved_by_manager')

    # ### end Alembic commands ###
