"""assign goals to manager

Revision ID: d321572794ba
Revises: 530e0d3d7703
Create Date: 2024-02-28 00:19:07.030756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd321572794ba'
down_revision = '530e0d3d7703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_goals')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_goals_manager_id_managers'), 'managers', ['manager_id'], ['id'])

    with op.batch_alter_table('tokenblocklist', schema=None) as batch_op:
        batch_op.drop_index('ix_tokenblocklist_jti')
        batch_op.create_index(batch_op.f('ix_tokenblocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenblocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenblocklist_jti'))
        batch_op.create_index('ix_tokenblocklist_jti', ['jti'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_goals_manager_id_managers'), type_='foreignkey')
        batch_op.drop_column('manager_id')

    op.create_table('_alembic_tmp_goals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('manager_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_goals_employee_id_employees'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name='fk_goals_manager_id_managers'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_goals_session_id_sessions'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
